apiVersion: apps/v1
kind: Deployment
metadata:
  name: mh-app
  labels:
    app: mh-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mh-app
  template:
    metadata:
      labels:
        app: mh-app
    spec:
      containers:
      - name: mh-web
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nfs-pvc-mh-web-1g
      volumes:
      - name: nfs-pvc-mh-web-1g
        persistentVolumeClaim:
          claimName: nfs-pvc-mh-web-1g

