apiVersion: apps/v1
kind: Deployment
metadata:
  name: mh-web-deployment
  labels:
    app: mh-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mh-web
  template:
    metadata:
      labels:
        app: mh-web
    spec:
      containers:
      - name: hello-mh
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nfs-pvc-mh-web-1g
      volumes:
      - name: nfs-pvc-mh-web-1g
        persistentVolumeClaim:
          claimName: nfs-pvc-mh-web-1g

        #name: mh-web-volume
#      volumes:
#      - name: mh-web-volume
#        nfs:
#          server: atom
#          path: /mnt/data1/kubernetes/mh-web
#          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: mh-web-service
spec:
  type: NodePort
  selector:
    app: mh-web
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30009
