---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mh-app
spec:
  selector:
    matchLabels:
      app: mh-app
  replicas: 1
  template:
    metadata:
      labels:
        app: mh-app
    spec:
      containers:
      - image: mediawiki
        name: mh-app
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/var/www/html/images"
            name: mh-app-pvc-storage
          - mountPath: "/opt/configfile"
            name: mh-app-config
      volumes:
      - name: mh-app-pvc-storage
        persistentVolumeClaim:
          claimName: mh-app-pvc-1g
      - name: mh-app-config
        persistentVolumeClaim:
          claimName: mh-app-config-1g
