---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mh-app
spec:
  selector:
    matchLabels:
      app: mh-app
  replicas: 1
  template:
    metadata:
      labels:
        app: mh-app
    spec:
      containers:
      - image: mediawiki
        name: mh-app
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/var/www/html/images"
            name: mh-app-pvc-storage
          - name: config-volume
            mountPath: /var/www/html/LocalSettings.php
      volumes:
      - name: mh-app-pvc-storage
        persistentVolumeClaim:
          claimName: mh-app-pvc-1g
      - name: config-volume
        configMap:
          name: mediawiki
          items:
          - key: LocalSettings.php
