apiVersion: apps/v1
kind: Deployment # what to create?
metadata:
  name: phpmyadmin-deployment
spec: # specification for deployment resource
  replicas: 1 # how many replicas of pods we want to create
  selector:
    matchLabels:
      app: phpmyadmin
  template: # blueprint for pods
    metadata:
      labels:
        app: phpmyadmin # service will look for this label
    spec: # specification for Pods
      containers:
      - name: phpmyadmin
        image: bitnami/phpmyadmin:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: mariadb-configmap
              key: database_url
