---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mh-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mh-app
  template:
    metadata:
      labels:
        app: mh-app
    spec:
      containers:
      - image: mediawiki
        name: mh-app
        ports:
        - containerPort: 80