apiVersion: v1
kind: PersistentVolume
metadata:
  name: mh-db-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  mountOptions:
    - hard
  nfs:
    path: /mnt/data1/kubernetes/mh-wiki-db
    server: atom.hedberg.life
