---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mh-app
spec:
  volumes:
    - name: mh-app-pvc-storage
      persistentVolumeClaim:
        claimName: nfs-pvc-mh-web-1g
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mh-app
  template:
    metadata:
      labels:
        app: mh-app
    spec:
      containers:
      - image: mediawiki
        name: mh-app
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/var/www/html/images"
            name: mh-app-pvc-storage
